sealed abstract class GrammarNode[Ctx, T]
case class Eps[Ctx]() extends GrammarNode[Ctx, Unit]
case class Character[Ctx](c: Char) extends GrammarNode[Ctx, Char]
case class Bot[Ctx]() extends GrammarNode[Ctx, Nothing]
case class Seq[Ctx, T, U](left: GrammarNode[Ctx, T], right: GrammarNode[Ctx, U]) extends GrammarNode[Ctx, (T, U)]
case class Alt[Ctx, T](left: GrammarNode[Ctx, T], right: GrammarNode[Ctx, T]) extends GrammarNode[Ctx, T]
case class Star[Ctx, T](a: GrammarNode[Ctx, T]) extends GrammarNode[Ctx, T]
case class Fix[Ctx, T](a: GrammarNode[(T, Ctx), T]) extends GrammarNode[Ctx, T]
case class Var[Ctx, T](v: DBVar[Ctx, T]) extends GrammarNode[Ctx, T]
case class Map[Ctx, T, U](f: T => U, a: GrammarNode[Ctx, T]) extends GrammarNode[Ctx, U]
